# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'RNNetwokState', :path => 'https://github.com/react-native-vietnam/react-native-network-state.git'

  # Pods for example
  target 'exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'example-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for example-tvOS

  target 'example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
